apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: hpa-auto-scale-simulation
spec:
  className: io.streamnative.simulators.FixedWorkSimulator
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  funcConfig:
    userConfig:
      strategy: io.streamnative.simulators.strategy.FindPrimes
      numInstances: 2
      launchDelay: 30
  replicas: 1
  maxReplicas: 8
  image: localhost:32000/fixed-work-simulator:0.0.3
  imagePullPolicy: Always
  logTopic: persistent://public/default/hpa-sim-log-80cpu
  input:
    topics:
      - persistent://public/default/trigger
    typeClassName: java.lang.String
  pulsar:
    pulsarConfig: "pulsar"
  pod:
    builtinAutoscaler:
      - AverageUtilizationCPUPercent80
  resources:
    requests:
      cpu: 500m
      memory: 512m
    limits:
      cpu: 2000m
      memory: 2G
  java:
    jar: /pulsar/fixed-work-simulator-0.0.3.jar
    # use "" to read jar from local file system
    jarLocation: ""
  clusterName: test-pulsar
  autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar
data:
  webServiceURL: http://192.168.1.100:8080
  brokerServiceURL: pulsar://192.168.1.100:6650
